version: "3"

services:
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    logging:
      driver: none

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - stocks-sort-vol:/data/db
    logging:
      driver: none

  b3:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://mongo:27017

volumes:
  stocks-sort-vol:
