version: '3'

services:
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - stocks-sort-net

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - stocks-sort-vol:/data/db
    networks:
      - stocks-sort-net

volumes:
  stocks-sort-vol:

networks:
    stocks-sort-net:
      driver: bridge
