version: '3'

services:
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - stocks-sort-vol/MongoDB:/data/db
    networks:
      - mongo-compose-network

volumes:
  stocks-sort-vol:

networks:
    mongo-compose-network:
      driver: bridge
